name: church_management_app
description: A church management system with admin and member dashboards.
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  cloud_functions: ^5.5.1
  firebase_storage: ^12.3.0
  firebase_messaging: ^15.2.5
  firebase_app_check: ^0.3.0

  # Location & Places (NEW)
  geolocator: ^13.0.1
  flutter_google_places_sdk: ^0.3.8

  # UI / notifications / charts
  flutter_local_notifications: ^20.0.0
  fl_chart: ^0.71.0
  font_awesome_flutter: ^10.6.0
  flutter_animate: ^4.5.2
  youtube_player_flutter: ^9.1.1
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.12

  # Payments
  flutter_stripe: ^9.3.0

  # Utils
  http: ^1.5.0
  intl: ^0.20.2
  provider: ^6.0.5
  another_flushbar: ^1.12.30
  path_provider: ^2.0.14
  go_router: ^14.0.0
  uuid: ^4.5.1
  html: ^0.15.4
  shared_preferences: ^2.3.2
  file_picker: ^8.0.3

  # Excel
  excel: ^4.0.6
  syncfusion_flutter_xlsio: ^29.1.38

  # Device/app info
  device_info_plus: ^11.1.0
  package_info_plus: ^8.0.2
  path: ^1.9.0
  image_picker: ^1.2.0
  url_launcher: ^6.3.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/female_avatar.png
    - assets/images/male_avatar.png
